version: '3'

services: 
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - /var/www:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: 
      context: ./php
    ports: 
      - 9000:9000
    volumes: 
      - /var/www:/code
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
     # - ./php/imagick.ini:/usr/local/etc/php/conf.d/imagick.ini
    environment: 
      MYSQL_USER: 'rad'
      MYSQL_PASSWORD: 'pass'
  
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    depends_on: 
      - php
    environment: 
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'mytest'
      MYSQL_USER: 'rad'
      MYSQL_PASSWORD: 'pass'